# A sample Gemfile
source "https://rubygems.org"

# gem "rails"

gem 'highline'
gem 'launchy'
gem 'plist4r'
gem 'trollop'
gem 'net-ssh'
gem 'net-sftp'
gem 'rbkb'
gem 'nokogiri'
gem 'sqlite3'
gem 'coderay'
gem 'qtbindings'
gem 'awesome_print'
gem 'ffi' # not really used atm.
gem 'htmlentities'
gem 'eventmachine'
gem 'log4r'
gem 'git'



